### ISSUE TITLE
2.12.x Minor Amendments

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#437]
Follow up with remaining items from #385 

- [x] [Rename 'Experiment code' as 'Study Period ID' with the description "The unique identifier for the study, for example 2020/R/CS/790."](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/456)
- [x]  [Rename 'Drilling Year' as 'Planting Year', and change the description to "The planting year for the study"](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/457)
- [x]  [Remove the 'People' tab (this has been replaced by the 'Researchers' on the experiment entity How does this affect permissions?](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/459)
- [x]  [Change the 'Experiment Plan' and 'Experiment Files' to links. Can we name links? Can we name links and use these as the name?](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/458)

New items for 2.12.x
- [x] #476
- [x] #475
- [x] #477
- [x] #478
- [x] [Experiment Design: Add previous cropping to Rotation tab](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/460)
- [x] [Experiment Program: Please add new funder](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/461)
- [x] [Experiment Program: Edit Grant Code data field](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/462)

**Comment by paul121** [comment]
this is largely done :-)
