### ISSUE TITLE
Experiment Module: Add Study Period ID to Proposals

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#648]
In order to fit this issue in before the end of the digital transformation I have had to simplify it slightly so that we are 

**SCHEDULED FOR MILESTONE 2.26.0:**
- [x] adding a study code to Proposals (issue #662) 
- [x] adding a filter/ column to the proposals for study ID (issue #773) 
- [x] checking it is called study ID on the experiments, and study plans (issue #751) 

**MOVED TO MONITOR:**
- [ ] Reviewing the bigger picture, including smaller tasks such as if this Study Period also be on the Designs in the way it is on the Experiments (moved to issue #775)

Although this is less than ideal for the user who has to enter the data multiple times it does at least we get it done by end of the project

**Initial (more complex) issue:**---------------------------------------------------------------------------------------------------------------

As the system has been used over the past year, I also now have a better idea of what people want to search by:

- Location
- Experiment Code/ Study Period ID
- Researcher
- Experiment Name
- Year

As such I have had several requests to add Experiment Code/ Study Period ID (depending how we work this and what we call it) to the filter tab for every Plan, Experiment, Design and Proposal. This includes the Plans tab (which is separate to the Research tab). This could ideally do with some additional thought in terms of visualisation and database structure. For example, the code is really an alternative to the name and flows through the experiments into plans (with the experiments ideally having their own code, although this doesn't work out in practice. 

This would also mean adding a Study Period ID to the Proposals _or_ building some clever search functionality. One request was a general search - so you can type in any key words and _all_ assets with those key words are listed.

**Comment by aislinnpearson** [comment]
Hey @paul121 - I've updated this with specific tasks but it doesn't display nicely in the milestones (you now have three issues instead of two, but it's still only two tasks. One to chat about maybe.

Let me know if the specifications for the sub-issues (tasks) are all good.

Thanks Paul,

Aislinn

**Comment by paul121** [comment]
I've completed both of these task sub-issues @aislinnpearson , I'll leave this parent feature issue for you to close after you review 👍

**Comment by aislinnpearson** [comment]
Okay, let's chat about that last issue this evening

**Comment by aislinnpearson** [comment]
Closed with #775 moved to monitor
